name: Windows Flutter Build

on:
  workflow_dispatch: # Allows you to trigger the build manually with a button

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Windows folder
        run: flutter create --platforms=windows .

      - name: Build Windows EXE
        run: flutter build windows --release
        env:
          PlatformToolset: v143

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-exe
          path: build/windows/x64/runner/Release/
